"""Mine the exact 60-card lists played by the highest-scoring leaderboard teams.

Deck swaps are the only change that has produced real gains twice (Abomasnow ->
Garchomp, Garchomp -> Ogerpon), so widening the candidate pool beyond the 10
archetype-modal lists is the cheapest remaining lever. Instead of one list per
archetype, take the list each TOP-SCORING TEAM actually played, across every
downloaded episode day.

Deck lists are public strategic data; no policy code is involved.
"""
from __future__ import annotations

import argparse
import csv
import glob
import json
import os
import sys
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "agent"))


def load_lb():
    pats = glob.glob(os.path.join(ROOT, "scratchpad", "**", "*publicleaderboard*.csv"),
                     recursive=True)
    lb = {}
    if pats:
        with open(sorted(pats)[-1], encoding="utf-8-sig") as fh:
            for r in csv.DictReader(fh):
                try:
                    lb[r["TeamName"].strip()] = float(r["Score"])
                except Exception:
                    pass
    return lb


def extract_decks(d):
    for p in d["steps"][0]:
        for viz in p.get("visualize") or []:
            f = [x for x in (viz.get("action") or [])
                 if isinstance(x, list) and len(x) == 60]
            if len(f) == 2:
                return f
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", type=int, default=50)
    ap.add_argument("--out", default=os.path.join(ROOT, "agent", "top_decks.py"))
    a = ap.parse_args()

    lb = load_lb()
    dirs = [os.path.join(ROOT, "data", "episodes")] + sorted(
        glob.glob(os.path.join(ROOT, "data", "ep_*")))
    files = []
    for d in dirs:
        files += glob.glob(os.path.join(d, "*.json"))
    print(f"{len(files)} episode files across {len(dirs)} days; {len(lb)} LB teams")

    # team -> Counter over exact 60-card lists they were seen playing
    team_lists = defaultdict(Counter)
    team_wins = defaultdict(lambda: [0, 0])
    for i, fp in enumerate(files):
        if i % 2000 == 0:
            print(f"  {i}/{len(files)}", flush=True)
        try:
            d = json.load(open(fp))
            dk = extract_decks(d)
            if not dk:
                continue
            teams = [t.strip() for t in ((d.get("info") or {}).get("TeamNames") or ["?", "?"])]
            rw = d.get("rewards") or []
            w = -1 if len(rw) != 2 or rw[0] == rw[1] else (0 if rw[0] > rw[1] else 1)
            for p in (0, 1):
                if lb.get(teams[p], -1) <= 0:
                    continue
                team_lists[teams[p]][tuple(dk[p])] += 1
                if w >= 0:
                    team_wins[teams[p]][1] += 1
                    team_wins[teams[p]][0] += int(w == p)
        except Exception:
            pass

    ranked = sorted(team_lists.items(), key=lambda kv: -lb.get(kv[0], 0))[:a.top]
    print(f"\n{len(ranked)} top teams with observed decks\n")

    seen = {}
    out = ['"""Exact 60-card lists played by the highest-scoring leaderboard teams.\n',
           'Mined from official replay dumps. Deck lists only -- public strategic data.',
           'Generated by tools/rank/mine_top_decks.py.\n"""\n']
    names = []
    for team, ctr in ranked:
        deck, n = ctr.most_common(1)[0]
        key = tuple(sorted(deck))
        score = lb.get(team, 0)
        w, g = team_wins[team]
        if key in seen:
            continue
        seen[key] = team
        var = "TD_%02d" % len(names)
        names.append((var, team, score, n, (100 * w / g) if g else 0))
        body = ",\n    ".join(", ".join(str(x) for x in list(deck)[i:i + 10])
                              for i in range(0, 60, 10))
        out.append(f"# {team[:40]} | LB {score:.1f} | seen {n}x | replay WR "
                   f"{(100*w/max(g,1)):.0f}%")
        out.append(f"{var} = [\n    {body},\n]\n")
    out.append("TOP_DECKS = {\n" + "".join(
        f'    "{v.lower()}": {v},  # LB {s:.0f}\n' for v, t, s, n, wr in names) + "}\n")
    open(a.out, "w").write("\n".join(out))
    print(f"wrote {a.out}: {len(names)} distinct decks")
    for v, t, s, n, wr in names[:15]:
        print(f"  {v}  LB {s:7.1f}  seen {n:4d}x  replayWR {wr:4.0f}%  {t[:34]}")


if __name__ == "__main__":
    main()
