#!/usr/bin/env python3
"""Emit one self-contained kernel directory per learner.

Kaggle script kernels upload a single code file, so a shared module cannot be
imported at run time and each variant has to carry the whole source. Generating
them from one source here keeps the two copies from drifting apart, which is the
failure mode that a hand-maintained duplicate always eventually hits.
"""
from pathlib import Path
import json

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SOURCE = (HERE / "experiment.py").read_text()
NEEDLE = 'LEARNER = "lgb"  # overwritten per-kernel by build_kernels.py'

for learner in ("lgb", "xgb"):
    assert SOURCE.count(NEEDLE) == 1, "learner marker missing or ambiguous"
    body = SOURCE.replace(
        NEEDLE, f'LEARNER = "{learner}"  # generated by build_kernels.py; edit the source')
    out = ROOT / f"cpu_kernel_hpo_{learner}"
    out.mkdir(exist_ok=True)
    (out / "experiment.py").write_text(body)
    (out / "kernel-metadata.json").write_text(json.dumps({
        "id": f"boltuzamaki/s6e8-cpu-hpo-{learner}-private",
        "title": f"S6E8 CPU HPO {learner} Private",
        "code_file": "experiment.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": False,
        "enable_internet": False,
        "competition_sources": ["playground-series-s6e8"],
    }, indent=2) + "\n")
    print(f"wrote {out}")
